version: '3'
services:
  chrome:
    image: alpeware/chrome-headless-trunk
    ports: 
      - "9222:9222"
    restart-policy: 
      condition: always
    volumes:
      - /tmp/chromedata:/data
    container_name: chrome